FROM openjdk:8-jre

MAINTAINER David Mejia <davidndy@gmail.com>

COPY . /node

#java -jar codeEvaluator/target/evaluator2-1.0.0.jar

ENTRYPOINT ["java","-jar","node/target/node-3-1.0.0.jar"]
#ENTRYPOINT ["bin/bash"]
